Fix incorrect label for stored state
canonical/prometheus-operator pull request #12
Opened 2020-11-12 20:30 UTC by balbirthomas

This commit fixes a typo that resulted from the recent merge
of alertmanager support commit. The stored state variable
should be named "_stored" but was instead "stored".

2020-11-12 20:31 UTC, justinmclark approved these changes

2020-11-12 20:39 UTC, justinmclark requested changes
This also needs to be changed in `test_charm.py`

2020-11-13 10:31 UTC, balbirthomas commented
> This also needs to be changed in `test_charm.py`


This also needs to be changed in test_charm.py

Please see my comments in https://github.com/canonical/prometheus-operator/pull/13 . Perhaps we should just merge this for now and let @dstathis create a separate pull request for fixing the tests.

2020-11-13 15:14 UTC, justinmclark approved these changes

2020-11-13 16:56 UTC, dstathis requested changes

2020-11-13 16:56 UTC, dstathis commented on tests/test_charm.py
> +        rel = self.harness.model.get_relation('alertmanager')
This should be alerting not alertmanager

2020-11-13 16:59 UTC, dstathis approved these changes

2020-11-13 16:59 UTC, merged